---
AWSTemplateFormatVersion: 2010-09-09
Description: Batch environments and queues
Parameters:
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: hpc
  IamStackName:
    Description: Set the IAM stack name.
    Type: String
    Default: iam-roles-for-batch-services
  VpcStackName:
    Description: Set the VPC stack name.
    Type: String
    Default: vpc-private-subnets-with-gateway-endpoints
Resources:
  # EC2 Launch Template (AL2)
  Ec2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${ProjectName}-ec2-launch-template
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 1000
              VolumeType: gp3
              Iops: 16000
              Throughput: 500
              Encrypted: true
              DeleteOnTermination: true
        InstanceInitiatedShutdownBehavior: terminate
  # Batch Compute Environments (Spot)
  BatchComputeEnvironmentFargateIntelSpot:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${ProjectName}-batch-compute-environment-fargate-intel-spot
      ComputeResources:
        MaxvCpus: 2048
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-DefaultSecurityGroup
        Type: FARGATE_SPOT
        Subnets:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
      ServiceRole:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchServiceRoleArn
      State: ENABLED
      Tags:
        Name: !Sub ${ProjectName}-batch-compute-environment-fargate-intel-spot
        ProjectName: !Ref ProjectName
  BatchComputeEnvironmentEc2GravitonSpot:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${ProjectName}-batch-compute-environment-ec2-graviton-spot
      ComputeResources:
        AllocationStrategy: SPOT_CAPACITY_OPTIMIZED
        BidPercentage: 100
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-DefaultSecurityGroup
        Type: SPOT
        LaunchTemplate:
          LaunchTemplateId: !Ref Ec2LaunchTemplate
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
        Ec2Configuration:
          - ImageType: ECS_AL2
        InstanceRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchEc2InstanceProfileArn
        SpotIamFleetRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchSpotFleetRoleArn
        InstanceTypes:
          - c7g
          - m6g
          - r6g
      ServiceRole:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchServiceRoleArn
      State: ENABLED
      Tags:
        Name: !Sub ${ProjectName}-batch-compute-environment-ec2-graviton-spot
        ProjectName: !Ref ProjectName
  BatchComputeEnvironmentEc2IntelSpot:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${ProjectName}-batch-compute-environment-ec2-intel-spot
      ComputeResources:
        AllocationStrategy: SPOT_CAPACITY_OPTIMIZED
        BidPercentage: 100
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-DefaultSecurityGroup
        Type: SPOT
        LaunchTemplate:
          LaunchTemplateId: !Ref Ec2LaunchTemplate
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
        Ec2Configuration:
          - ImageType: ECS_AL2
        InstanceRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchEc2InstanceProfileArn
        SpotIamFleetRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchSpotFleetRoleArn
        InstanceTypes:
          - m6i
          - c6i
          - r6i
      ServiceRole:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchServiceRoleArn
      State: ENABLED
      Tags:
        Name: !Sub ${ProjectName}-batch-compute-environment-ec2-intel-spot
        ProjectName: !Ref ProjectName
  BatchComputeEnvironmentEc2NvidiaSpot:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${ProjectName}-batch-compute-environment-ec2-nvidia-spot
      ComputeResources:
        AllocationStrategy: SPOT_CAPACITY_OPTIMIZED
        BidPercentage: 100
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-DefaultSecurityGroup
        Type: SPOT
        LaunchTemplate:
          LaunchTemplateId: !Ref Ec2LaunchTemplate
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
        Ec2Configuration:
          - ImageType: ECS_AL2_NVIDIA
        InstanceRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchEc2InstanceProfileArn
        SpotIamFleetRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchSpotFleetRoleArn
        InstanceTypes:
          - g5g   # g5
      ServiceRole:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchServiceRoleArn
      State: ENABLED
      Tags:
        Name: !Sub ${ProjectName}-batch-compute-environment-ec2-nvidia-spot
        ProjectName: !Ref ProjectName
  # Batch Job Queues (Spot)
  BatchJobQueueFargateIntelSpot:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Sub ${ProjectName}-batch-job-queue-fargate-intel-spot
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentFargateIntelSpot
      Priority: 1
      State: ENABLED
      Tags:
        Name: !Sub ${ProjectName}-batch-job-queue-fargate-intel-spot
        ProjectName: !Ref ProjectName
  BatchJobQueueEc2GravitonSpot:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Sub ${ProjectName}-batch-job-queue-ec2-graviton-spot
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2GravitonSpot
      Priority: 1
      State: ENABLED
      Tags:
        Name: !Sub ${ProjectName}-batch-job-queue-ec2-graviton-spot
        ProjectName: !Ref ProjectName
  BatchJobQueueEc2IntelSpot:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Sub ${ProjectName}-batch-job-queue-ec2-intel-spot
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2IntelSpot
      Priority: 1
      State: ENABLED
      Tags:
        Name: !Sub ${ProjectName}-batch-job-queue-ec2-intel-spot
        ProjectName: !Ref ProjectName
  BatchJobQueueEc2NvidiaSpot:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Sub ${ProjectName}-batch-job-queue-ec2-nvidia-spot
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2NvidiaSpot
      Priority: 1
      State: ENABLED
      Tags:
        Name: !Sub ${ProjectName}-batch-job-queue-ec2-nvidia-spot
        ProjectName: !Ref ProjectName
  # Batch Compute Environments (OnDemand)
  BatchComputeEnvironmentFargateIntelOnDemand:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${ProjectName}-batch-compute-environment-fargate-intel-ondemand
      ComputeResources:
        MaxvCpus: 2048
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-DefaultSecurityGroup
        Type: FARGATE
        Subnets:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
      ServiceRole:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchServiceRoleArn
      State: ENABLED
      Tags:
        Name: !Sub ${ProjectName}-batch-compute-environment-fargate-intel-ondemand
        ProjectName: !Ref ProjectName
  BatchComputeEnvironmentEc2GravitonOnDemand:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${ProjectName}-batch-compute-environment-ec2-graviton-ondemand
      ComputeResources:
        AllocationStrategy: BEST_FIT
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-DefaultSecurityGroup
        Type: EC2
        LaunchTemplate:
          LaunchTemplateId: !Ref Ec2LaunchTemplate
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
        Ec2Configuration:
          - ImageType: ECS_AL2
        InstanceRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchEc2InstanceProfileArn
        InstanceTypes:
          - c7g
          - m6g
          - r6g
      ServiceRole:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchServiceRoleArn
      State: ENABLED
      Tags:
        Name: !Sub ${ProjectName}-batch-compute-environment-ec2-graviton-ondemand
        ProjectName: !Ref ProjectName
  BatchComputeEnvironmentEc2IntelOnDemand:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${ProjectName}-batch-compute-environment-ec2-intel-ondemand
      ComputeResources:
        AllocationStrategy: BEST_FIT
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-DefaultSecurityGroup
        Type: EC2
        LaunchTemplate:
          LaunchTemplateId: !Ref Ec2LaunchTemplate
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
        Ec2Configuration:
          - ImageType: ECS_AL2
        InstanceRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchEc2InstanceProfileArn
        InstanceTypes:
          - m6i
          - c6i
          - r6i
      ServiceRole:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchServiceRoleArn
      State: ENABLED
      Tags:
        Name: !Sub ${ProjectName}-batch-compute-environment-ec2-intel-ondemand
        ProjectName: !Ref ProjectName
  BatchComputeEnvironmentEc2NvidiaOnDemand:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${ProjectName}-batch-compute-environment-ec2-nvidia-ondemand
      ComputeResources:
        AllocationStrategy: BEST_FIT
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-DefaultSecurityGroup
        Type: EC2
        LaunchTemplate:
          LaunchTemplateId: !Ref Ec2LaunchTemplate
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
        Ec2Configuration:
          - ImageType: ECS_AL2_NVIDIA
        InstanceRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchEc2InstanceProfileArn
        InstanceTypes:
          - g5g   # g5
      ServiceRole:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchServiceRoleArn
      State: ENABLED
      Tags:
        Name: !Sub ${ProjectName}-batch-compute-environment-ec2-nvidia-ondemand
        ProjectName: !Ref ProjectName
  # Batch Job Queues (OnDemand)
  BatchJobQueueFargateIntelOnDemand:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Sub ${ProjectName}-batch-job-queue-fargate-intel-ondemand
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentFargateIntelOnDemand
      Priority: 1
      State: ENABLED
      Tags:
        Name: !Sub ${ProjectName}-batch-job-queue-fargate-intel-ondemand
        ProjectName: !Ref ProjectName
  BatchJobQueueEc2GravitonOnDemand:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Sub ${ProjectName}-batch-job-queue-ec2-graviton-ondemand
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2GravitonOnDemand
      Priority: 1
      State: ENABLED
      Tags:
        Name: !Sub ${ProjectName}-batch-job-queue-ec2-graviton-ondemand
        ProjectName: !Ref ProjectName
  BatchJobQueueEc2IntelOnDemand:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Sub ${ProjectName}-batch-job-queue-ec2-intel-ondemand
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2IntelOnDemand
      Priority: 1
      State: ENABLED
      Tags:
        Name: !Sub ${ProjectName}-batch-job-queue-ec2-intel-ondemand
        ProjectName: !Ref ProjectName
  BatchJobQueueEc2NvidiaOnDemand:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Sub ${ProjectName}-batch-job-queue-ec2-nvidia-ondemand
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2NvidiaOnDemand
      Priority: 1
      State: ENABLED
      Tags:
        Name: !Sub ${ProjectName}-batch-job-queue-ec2-nvidia-ondemand
        ProjectName: !Ref ProjectName
  BatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/batch/${ProjectName}-batch-job
      RetentionInDays: 14
      Tags:
        - Key: Name
          Value: !Sub /aws/batch/${ProjectName}-batch-job
        - Key: ProjectName
          Value: !Ref ProjectName
Outputs:
  Ec2LaunchTemplate:
    Value: !Ref Ec2LaunchTemplate
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-Ec2LaunchTemplate
  BatchComputeEnvironmentFargateIntelSpot:
    Value: !Ref BatchComputeEnvironmentFargateIntelSpot
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchComputeEnvironmentFargateIntelSpot
  BatchComputeEnvironmentEc2GravitonSpot:
    Value: !Ref BatchComputeEnvironmentEc2GravitonSpot
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchComputeEnvironmentEc2GravitonSpot
  BatchComputeEnvironmentEc2IntelSpot:
    Value: !Ref BatchComputeEnvironmentEc2IntelSpot
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchComputeEnvironmentEc2IntelSpot
  BatchComputeEnvironmentEc2NvidiaSpot:
    Value: !Ref BatchComputeEnvironmentEc2NvidiaSpot
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchComputeEnvironmentEc2NvidiaSpot
  BatchJobQueueFargateIntelSpot:
    Value: !Ref BatchJobQueueFargateIntelSpot
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchJobQueueFargateIntelSpot
  BatchJobQueueEc2GravitonSpot:
    Value: !Ref BatchJobQueueEc2GravitonSpot
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchJobQueueEc2GravitonSpot
  BatchJobQueueEc2IntelSpot:
    Value: !Ref BatchJobQueueEc2IntelSpot
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchJobQueueEc2IntelSpot
  BatchJobQueueEc2NvidiaSpot:
    Value: !Ref BatchJobQueueEc2NvidiaSpot
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchJobQueueEc2NvidiaSpot
  BatchComputeEnvironmentFargateIntelOnDemand:
    Value: !Ref BatchComputeEnvironmentFargateIntelOnDemand
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchComputeEnvironmentFargateIntelOnDemand
  BatchComputeEnvironmentEc2GravitonOnDemand:
    Value: !Ref BatchComputeEnvironmentEc2GravitonOnDemand
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchComputeEnvironmentEc2GravitonOnDemand
  BatchComputeEnvironmentEc2IntelOnDemand:
    Value: !Ref BatchComputeEnvironmentEc2IntelOnDemand
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchComputeEnvironmentEc2IntelOnDemand
  BatchComputeEnvironmentEc2NvidiaOnDemand:
    Value: !Ref BatchComputeEnvironmentEc2NvidiaOnDemand
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchComputeEnvironmentEc2NvidiaOnDemand
  BatchJobQueueFargateIntelOnDemand:
    Value: !Ref BatchJobQueueFargateIntelOnDemand
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchJobQueueFargateIntelOnDemand
  BatchJobQueueEc2GravitonOnDemand:
    Value: !Ref BatchJobQueueEc2GravitonOnDemand
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchJobQueueEc2GravitonOnDemand
  BatchJobQueueEc2IntelOnDemand:
    Value: !Ref BatchJobQueueEc2IntelOnDemand
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchJobQueueEc2IntelOnDemand
  BatchJobQueueEc2NvidiaOnDemand:
    Value: !Ref BatchJobQueueEc2NvidiaOnDemand
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchJobQueueEc2NvidiaOnDemand
  BatchLogGroup:
    Value: !Ref BatchLogGroup
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchLogGroup
