---
AWSTemplateFormatVersion: 2010-09-09
Description: Batch for high-performance computing
Parameters:
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: slhpc
  IamStackName:
    Description: Set the IAM Stack Name.
    Type: String
    Default: slhpc-iam-roles-for-batch-services
  VpcStackName:
    Description: Set the VPC Stack Name.
    Type: String
    Default: vpc-private-subnets-and-s3-endpoint
Resources:
  # EC2 Launch Template (AL2)
  Ec2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${ProjectName}-ec2-launch-template
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 2000
              VolumeType: gp3
              Iops: 16000
              Throughput: 500
              Encrypted: true
              DeleteOnTermination: true
        InstanceInitiatedShutdownBehavior: terminate
  # Batch Compute Environments (Spot)
  BatchComputeEnvironmentFargateSpot:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${ProjectName}-batch-compute-environment-fargate-spot
      ComputeResources:
        MaxvCpus: 2048
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${VpcPrivateStackName}-DefaultSecurityGroup
        Type: FARGATE_SPOT
        Subnets:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
      ServiceRole:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchServiceRole
      State: ENABLED
  BatchComputeEnvironmentEc2GravitonSpot:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${ProjectName}-batch-compute-environment-ec2-graviton-spot
      ComputeResources:
        AllocationStrategy: SPOT_CAPACITY_OPTIMIZED
        BidPercentage: 100
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${VpcPrivateStackName}-DefaultSecurityGroup
        Type: SPOT
        LaunchTemplate:
          LaunchTemplateId: !Ref Ec2LaunchTemplate
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
        Ec2Configuration:
          - ImageType: ECS_AL2
        InstanceRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchEc2InstanceProfile
        SpotIamFleetRole: !Sub ${AWS::Region}-${IamStackName}-BatchSpotFleetRole
        InstanceTypes:
          - c7g
          - m6g
          - r6g
      ServiceRole:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchServiceRole
      State: ENABLED
  BatchComputeEnvironmentEc2IntelSpot:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${ProjectName}-batch-compute-environment-ec2-intel-spot
      ComputeResources:
        AllocationStrategy: SPOT_CAPACITY_OPTIMIZED
        BidPercentage: 100
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${VpcPrivateStackName}-DefaultSecurityGroup
        Type: SPOT
        LaunchTemplate:
          LaunchTemplateId: !Ref Ec2LaunchTemplate
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
        Ec2Configuration:
          - ImageType: ECS_AL2
        InstanceRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchEc2InstanceProfile
        SpotIamFleetRole: !Sub ${AWS::Region}-${IamStackName}-BatchSpotFleetRole
        InstanceTypes:
          - m6i
          - c6i
          - r6i
      ServiceRole:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchServiceRole
      State: ENABLED
  BatchComputeEnvironmentEc2NvidiaSpot:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${ProjectName}-batch-compute-environment-ec2-nvidia-spot
      ComputeResources:
        AllocationStrategy: SPOT_CAPACITY_OPTIMIZED
        BidPercentage: 100
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${VpcPrivateStackName}-DefaultSecurityGroup
        Type: SPOT
        LaunchTemplate:
          LaunchTemplateId: !Ref Ec2LaunchTemplate
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
        Ec2Configuration:
          - ImageType: ECS_AL2_NVIDIA
        InstanceRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchEc2InstanceProfile
        SpotIamFleetRole: !Sub ${AWS::Region}-${IamStackName}-BatchSpotFleetRole
        InstanceTypes:
          - g5g
      ServiceRole:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchServiceRole
      State: ENABLED
  # Batch Job Queues (Spot)
  BatchJobQueueFargateSpot:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentFargateSpot
      JobQueueName: !Sub ${ProjectName}-batch-job-queue-fargate-spot
      Priority: 1
      State: ENABLED
  BatchJobQueueEc2GravitonSpot:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2GravitonSpot
      JobQueueName: !Sub ${ProjectName}-batch-job-queue-ec2-graviton-spot
      Priority: 1
      State: ENABLED
  BatchJobQueueEc2IntelSpot:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2IntelSpot
      JobQueueName: !Sub ${ProjectName}-batch-job-queue-ec2-intel-spot
      Priority: 1
      State: ENABLED
  BatchJobQueueEc2NvidiaSpot:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2NvidiaSpot
      JobQueueName: !Sub ${ProjectName}-batch-job-queue-ec2-nvidia-spot
      Priority: 1
      State: ENABLED
  # Batch Compute Environments (OnDemand)
  BatchComputeEnvironmentFargateOnDemand:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${ProjectName}-batch-compute-environment-fargate-ondemand
      ComputeResources:
        MaxvCpus: 2048
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${VpcPrivateStackName}-DefaultSecurityGroup
        Type: FARGATE
        Subnets:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
      ServiceRole:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchServiceRole
      State: ENABLED
  BatchComputeEnvironmentEc2GravitonOnDemand:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${ProjectName}-batch-compute-environment-ec2-graviton-ondemand
      ComputeResources:
        AllocationStrategy: BEST_FIT
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${VpcPrivateStackName}-DefaultSecurityGroup
        Type: EC2
        LaunchTemplate:
          LaunchTemplateId: !Ref Ec2LaunchTemplate
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
        Ec2Configuration:
          - ImageType: ECS_AL2
        InstanceRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchEc2InstanceProfile
        InstanceTypes:
          - c7g
          - m6g
          - r6g
      ServiceRole:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchServiceRole
      State: ENABLED
  BatchComputeEnvironmentEc2IntelOnDemand:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${ProjectName}-batch-compute-environment-ec2-intel-ondemand
      ComputeResources:
        AllocationStrategy: BEST_FIT
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${VpcPrivateStackName}-DefaultSecurityGroup
        Type: EC2
        LaunchTemplate:
          LaunchTemplateId: !Ref Ec2LaunchTemplate
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
        Ec2Configuration:
          - ImageType: ECS_AL2
        InstanceRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchEc2InstanceProfile
        InstanceTypes:
          - m6i
          - c6i
          - r6i
      ServiceRole:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchServiceRole
      State: ENABLED
  BatchComputeEnvironmentEc2NvidiaOnDemand:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub ${ProjectName}-batch-compute-environment-ec2-nvidia-ondemand
      ComputeResources:
        AllocationStrategy: BEST_FIT
        MinvCpus: 0
        MaxvCpus: 2048
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${VpcPrivateStackName}-DefaultSecurityGroup
        Type: EC2
        LaunchTemplate:
          LaunchTemplateId: !Ref Ec2LaunchTemplate
          Version: $Latest
        Subnets:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
        Ec2Configuration:
          - ImageType: ECS_AL2_NVIDIA
        InstanceRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchEc2InstanceProfile
        InstanceTypes:
          - g5g
      ServiceRole:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-BatchServiceRole
      State: ENABLED
  # Batch Job Queues (OnDemand)
  BatchJobQueueFargateOnDemand:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentFargateOnDemand
      JobQueueName: !Sub ${ProjectName}-batch-job-queue-fargate-ondemand
      Priority: 1
      State: ENABLED
  BatchJobQueueEc2GravitonOnDemand:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2GravitonOnDemand
      JobQueueName: !Sub ${ProjectName}-batch-job-queue-ec2-graviton-ondemand
      Priority: 1
      State: ENABLED
  BatchJobQueueEc2IntelOnDemand:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2IntelOnDemand
      JobQueueName: !Sub ${ProjectName}-batch-job-queue-ec2-intel-ondemand
      Priority: 1
      State: ENABLED
  BatchJobQueueEc2NvidiaOnDemand:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BatchComputeEnvironmentEc2NvidiaOnDemand
      JobQueueName: !Sub ${ProjectName}-batch-job-queue-ec2-nvidia-ondemand
      Priority: 1
      State: ENABLED
Outputs:
  Ec2LaunchTemplate:
    Value: !Ref Ec2LaunchTemplate
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-Ec2LaunchTemplate
  BatchComputeEnvironmentFargateSpot:
    Value: !Ref BatchComputeEnvironmentFargateSpot
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchComputeEnvironmentFargateSpot
  BatchComputeEnvironmentEc2GravitonSpot:
    Value: !Ref BatchComputeEnvironmentEc2GravitonSpot
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchComputeEnvironmentEc2GravitonSpot
  BatchComputeEnvironmentEc2IntelSpot:
    Value: !Ref BatchComputeEnvironmentEc2IntelSpot
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchComputeEnvironmentEc2IntelSpot
  BatchComputeEnvironmentEc2NvidiaSpot:
    Value: !Ref BatchComputeEnvironmentEc2NvidiaSpot
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchComputeEnvironmentEc2NvidiaSpot
  BatchJobQueueFargateSpot:
    Value: !Ref BatchJobQueueFargateSpot
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchJobQueueFargateSpot
  BatchJobQueueEc2GravitonSpot:
    Value: !Ref BatchJobQueueEc2GravitonSpot
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchJobQueueEc2GravitonSpot
  BatchJobQueueEc2IntelSpot:
    Value: !Ref BatchJobQueueEc2IntelSpot
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchJobQueueEc2IntelSpot
  BatchJobQueueEc2NvidiaSpot:
    Value: !Ref BatchJobQueueEc2NvidiaSpot
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchJobQueueEc2NvidiaSpot
  BatchComputeEnvironmentFargateOnDemand:
    Value: !Ref BatchComputeEnvironmentFargateOnDemand
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchComputeEnvironmentFargateOnDemand
  BatchComputeEnvironmentEc2GravitonOnDemand:
    Value: !Ref BatchComputeEnvironmentEc2GravitonOnDemand
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchComputeEnvironmentEc2GravitonOnDemand
  BatchComputeEnvironmentEc2IntelOnDemand:
    Value: !Ref BatchComputeEnvironmentEc2IntelOnDemand
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchComputeEnvironmentEc2IntelOnDemand
  BatchComputeEnvironmentEc2NvidiaOnDemand:
    Value: !Ref BatchComputeEnvironmentEc2NvidiaOnDemand
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchComputeEnvironmentEc2NvidiaOnDemand
  BatchJobQueueFargateOnDemand:
    Value: !Ref BatchJobQueueFargateOnDemand
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchJobQueueFargateOnDemand
  BatchJobQueueEc2GravitonOnDemand:
    Value: !Ref BatchJobQueueEc2GravitonOnDemand
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchJobQueueEc2GravitonOnDemand
  BatchJobQueueEc2IntelOnDemand:
    Value: !Ref BatchJobQueueEc2IntelOnDemand
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchJobQueueEc2IntelOnDemand
  BatchJobQueueEc2NvidiaOnDemand:
    Value: !Ref BatchJobQueueEc2NvidiaOnDemand
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-BatchJobQueueEc2NvidiaOnDemand
