---
AWSTemplateFormatVersion: 2010-09-09
Description: Chatbot and SNS for Step Functions
Parameters:
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: slhpc
  SnsTopicName:
    Description: Set the SNS topic name.
    Type: String
    Default: states-topic
  SlackWorkspaceId:
    Description: Set the Slack workspace ID.
    Type: String
    Default: XXXXXXXXX
  SlackChannelId:
    Description: Set the Slack channel ID for AWS Step Functions.
    Type: String
    Default: awsstepfunctions
Resources:
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${SnsTopicName}
  SnsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref SnsTopic
      Topics:
        - !Ref SnsTopic
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${SnsTopicName}-event-rule
      EventPattern:
        source:
          - aws.states
      Targets:
        - Arn: !Ref SnsTopic
          Id: states-sns-topic
  ChatbotConfiguration:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties:
      ConfigurationName: !Sub ${ProjectName}-states-topic-chatbot-config
      IamRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/management.chatbot.amazonaws.com/AWSServiceRoleForAWSChatbot
      LoggingLevel: NONE
      SlackChannelId: !Ref SlackChannelId
      SlackWorkspaceId: !Ref SlackWorkspaceId
      SnsTopicArns:
        - !Ref SnsTopic
