---
AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template for IAM Roles
Parameters:
  SystemName:
    Description: System Name.
    Type: String
    Default: iobatch
  EnvType:
    Description: Environment Type.
    Type: String
    Default: dev
  S3StackName:
    Description: S3 Stack Name.
    Type: String
    Default: iobatch-dev-s3
Resources:
  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-BatchServiceRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - batch.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /service-role/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole
  BatchJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-BatchJobRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${SystemName}-${EnvType}-BatchJobRole-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource:
                  'Fn::Join':
                    - ''
                    - - 'arn:aws:s3:::'
                      - 'Fn::ImportValue': !Sub ${S3StackName}-InputBucket
                      - /*
                Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
              - Resource:
                  'Fn::Join':
                    - ''
                    - - 'arn:aws:s3:::'
                      - 'Fn::ImportValue': !Sub ${S3StackName}-ReferenceBucket
                      - /*
                Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
              - Resource:
                  'Fn::Join':
                    - ''
                    - - 'arn:aws:s3:::'
                      - 'Fn::ImportValue': !Sub ${S3StackName}-OutputBucket
                      - /*
                Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:PutObject
              - Resource:
                  'Fn::Join':
                    - ''
                    - - 'arn:aws:s3:::'
                      - 'Fn::ImportValue': !Sub ${S3StackName}-ArchiveBucket
                      - /*
                Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:PutObject
  BatchJobExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-BatchJobExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  BatchInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-BatchInstanceRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
  BatchInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: BatchInstanceRole
Outputs:
  BatchServiceRole:
    Value: !GetAtt BatchServiceRole.Arn
    Description: BatchServiceRole
    Export:
      Name: !Sub ${AWS::StackName}-BatchServiceRole
  BatchJobRole:
    Value: !GetAtt BatchJobRole.Arn
    Description: BatchJobRole
    Export:
      Name: !Sub ${AWS::StackName}-BatchJobRole
  BatchJobExecutionRole:
    Value: !GetAtt BatchJobExecutionRole.Arn
    Description: BatchJobExecutionRole
    Export:
      Name: !Sub ${AWS::StackName}-BatchJobExecutionRole
  BatchInstanceRole:
    Value: !GetAtt BatchInstanceRole.Arn
    Description: BatchInstanceRole
    Export:
      Name: !Sub ${AWS::StackName}-BatchInstanceRole
  BatchInstanceProfile:
    Value: !GetAtt BatchInstanceProfile.Arn
    Description: BatchInstanceProfile
    Export:
      Name: !Sub ${AWS::StackName}-BatchInstanceProfile
